import React, { useRef } from 'react';
import {
  View, Text, StyleSheet, TouchableOpacity, ScrollView,
  Dimensions, Animated,
} from 'react-native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons } from '@expo/vector-icons';
import { StatusBar } from 'expo-status-bar';
import { Colors } from '../theme/colors';
import { AuthStackParamList } from '../types';

type Props = {
  navigation: NativeStackNavigationProp<AuthStackParamList, 'Landing'>;
};

const { width } = Dimensions.get('window');

const FEATURES = [
  {
    icon: 'sparkles' as const,
    color: Colors.primary,
    title: 'Adaptive AI Curriculum',
    desc: 'Personalized learning paths generated by AI based on your level, goals, and learning style.',
  },
  {
    icon: 'chatbubbles' as const,
    color: Colors.accent,
    title: 'Interactive AI Tutor',
    desc: 'Ask questions, get explanations, and learn through real-time conversation with your AI tutor.',
  },
  {
    icon: 'bar-chart' as const,
    color: Colors.success,
    title: 'Real-time Analytics',
    desc: 'Track your progress, streaks, engagement scores, and get early risk alerts.',
  },
  {
    icon: 'videocam' as const,
    color: Colors.warning,
    title: 'Engagement Detection',
    desc: 'AI monitors attention and adapts content pacing based on your focus in real time.',
  },
];

const STATS = [
  { value: '10K+', label: 'Active Students' },
  { value: '50+', label: 'Subjects' },
  { value: '98%', label: 'Satisfaction' },
];

export default function LandingScreen({ navigation }: Props) {
  const scrollY = useRef(new Animated.Value(0)).current;

  const heroOpacity = scrollY.interpolate({
    inputRange: [0, 200],
    outputRange: [1, 0],
    extrapolate: 'clamp',
  });

  return (
    <View style={styles.container}>
      <StatusBar style="light" />

      <Animated.ScrollView
        showsVerticalScrollIndicator={false}
        onScroll={Animated.event([{ nativeEvent: { contentOffset: { y: scrollY } } }], {
          useNativeDriver: true,
        })}
        scrollEventThrottle={16}
      >
        {/* Hero */}
        <LinearGradient colors={Colors.gradientHero as unknown as string[]} style={styles.hero}>
          <Animated.View style={[styles.heroContent, { opacity: heroOpacity }]}>
            <View style={styles.logoBadge}>
              <LinearGradient colors={Colors.gradientPrimary as unknown as string[]} style={styles.logoIcon}>
                <Ionicons name="school" size={28} color={Colors.white} />
              </LinearGradient>
              <Text style={styles.logoText}>EduAI OS</Text>
            </View>

            <Text style={styles.heroTitle}>
              Learn Smarter with{'\n'}
              <Text style={styles.heroGradientText}>AI-Powered</Text>
              {'\n'}Education
            </Text>

            <Text style={styles.heroSubtitle}>
              Netflix-style personalized learning from secondary school through university.
              Adaptive curriculum, real-time tutor, and engagement analytics.
            </Text>

            {/* Stats row */}
            <View style={styles.statsRow}>
              {STATS.map((stat) => (
                <View key={stat.label} style={styles.statItem}>
                  <Text style={styles.statValue}>{stat.value}</Text>
                  <Text style={styles.statLabel}>{stat.label}</Text>
                </View>
              ))}
            </View>

            {/* CTA Buttons */}
            <TouchableOpacity
              style={styles.ctaPrimary}
              onPress={() => navigation.navigate('Register')}
              activeOpacity={0.85}
            >
              <LinearGradient colors={Colors.gradientPrimary as unknown as string[]} style={styles.ctaGradient}>
                <Text style={styles.ctaPrimaryText}>Get Started Free</Text>
                <Ionicons name="arrow-forward" size={18} color={Colors.white} style={{ marginLeft: 8 }} />
              </LinearGradient>
            </TouchableOpacity>

            <TouchableOpacity
              style={styles.ctaSecondary}
              onPress={() => navigation.navigate('Login')}
              activeOpacity={0.85}
            >
              <Text style={styles.ctaSecondaryText}>Sign In to Your Account</Text>
            </TouchableOpacity>
          </Animated.View>

          {/* Floating cards decoration */}
          <View style={styles.floatingCards}>
            <View style={[styles.floatingCard, styles.floatingCard1]}>
              <Ionicons name="school-outline" size={20} color={Colors.primaryLight} />
              <Text style={styles.floatingCardText}>O-Level</Text>
            </View>
            <View style={[styles.floatingCard, styles.floatingCard2]}>
              <Ionicons name="sparkles-outline" size={20} color={Colors.accent} />
              <Text style={[styles.floatingCardText, { color: Colors.accent }]}>AI Tutor</Text>
            </View>
            <View style={[styles.floatingCard, styles.floatingCard3]}>
              <Ionicons name="trophy-outline" size={20} color={Colors.success} />
              <Text style={[styles.floatingCardText, { color: Colors.success }]}>Top Scorer</Text>
            </View>
          </View>
        </LinearGradient>

        {/* Features Section */}
        <View style={styles.featuresSection}>
          <Text style={styles.sectionTitle}>Everything You Need to Excel</Text>
          <Text style={styles.sectionSubtitle}>
            A complete AI-powered OS for modern learners
          </Text>

          <View style={styles.featuresGrid}>
            {FEATURES.map((feature) => (
              <View key={feature.title} style={styles.featureCard}>
                <View style={[styles.featureIcon, { backgroundColor: feature.color + '20' }]}>
                  <Ionicons name={feature.icon} size={28} color={feature.color} />
                </View>
                <Text style={styles.featureTitle}>{feature.title}</Text>
                <Text style={styles.featureDesc}>{feature.desc}</Text>
              </View>
            ))}
          </View>
        </View>

        {/* Education levels */}
        <View style={styles.levelsSection}>
          <Text style={styles.sectionTitle}>For Every Level of Learning</Text>
          {[
            { title: 'Secondary School', sub: 'O-Level & A-Level (NECTA)', icon: 'school', color: Colors.primary },
            { title: 'College', sub: 'Certificate, Diploma, Higher Diploma (NACTE)', icon: 'library', color: Colors.accent },
            { title: 'University', sub: 'Undergraduate & Postgraduate', icon: 'business', color: Colors.success },
          ].map((level) => (
            <View key={level.title} style={styles.levelCard}>
              <View style={[styles.levelIcon, { backgroundColor: level.color + '20' }]}>
                <Ionicons name={level.icon as keyof typeof Ionicons.glyphMap} size={24} color={level.color} />
              </View>
              <View style={styles.levelText}>
                <Text style={styles.levelTitle}>{level.title}</Text>
                <Text style={styles.levelSub}>{level.sub}</Text>
              </View>
              <Ionicons name="chevron-forward" size={20} color={Colors.textMuted} />
            </View>
          ))}
        </View>

        {/* Bottom CTA */}
        <LinearGradient colors={['#1a0a3e', '#0a0a0f']} style={styles.bottomCta}>
          <Text style={styles.bottomCtaTitle}>Ready to Transform Your Learning?</Text>
          <Text style={styles.bottomCtaSub}>Join 10,000+ students already learning smarter</Text>
          <TouchableOpacity onPress={() => navigation.navigate('Register')} activeOpacity={0.85}>
            <LinearGradient colors={Colors.gradientPrimary as unknown as string[]} style={styles.bottomCtaBtn}>
              <Text style={styles.ctaPrimaryText}>Start Learning Today</Text>
            </LinearGradient>
          </TouchableOpacity>
        </LinearGradient>
      </Animated.ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.bg },
  hero: {
    paddingTop: 60,
    paddingBottom: 48,
    paddingHorizontal: 24,
    minHeight: 600,
  },
  heroContent: { alignItems: 'center' },
  logoBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 32,
    backgroundColor: Colors.primaryAlpha,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: Colors.primary + '40',
  },
  logoIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  logoText: { fontSize: 18, fontWeight: '700', color: Colors.text },
  heroTitle: {
    fontSize: 36,
    fontWeight: '800',
    color: Colors.text,
    textAlign: 'center',
    lineHeight: 48,
    marginBottom: 16,
  },
  heroGradientText: {
    color: Colors.primaryLight,
  },
  heroSubtitle: {
    fontSize: 15,
    color: Colors.textSecondary,
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 32,
    paddingHorizontal: 8,
  },
  statsRow: {
    flexDirection: 'row',
    gap: 24,
    marginBottom: 32,
  },
  statItem: { alignItems: 'center' },
  statValue: { fontSize: 24, fontWeight: '800', color: Colors.text },
  statLabel: { fontSize: 11, color: Colors.textSecondary, marginTop: 2 },
  ctaPrimary: {
    width: width - 48,
    borderRadius: 16,
    overflow: 'hidden',
    marginBottom: 12,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 12,
  },
  ctaGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 18,
  },
  ctaPrimaryText: { fontSize: 16, fontWeight: '700', color: Colors.white },
  ctaSecondary: {
    paddingVertical: 14,
    paddingHorizontal: 24,
  },
  ctaSecondaryText: {
    fontSize: 15,
    color: Colors.textSecondary,
    textDecorationLine: 'underline',
  },
  floatingCards: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    width: 0,
    overflow: 'visible',
  },
  floatingCard: {
    position: 'absolute',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: Colors.bgCard + 'ee',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  floatingCard1: { top: 80, right: -120 },
  floatingCard2: { top: 200, right: -100 },
  floatingCard3: { top: 320, right: -130 },
  floatingCardText: { fontSize: 12, color: Colors.primaryLight, fontWeight: '600' },

  featuresSection: { padding: 24 },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: Colors.text,
    textAlign: 'center',
    marginBottom: 8,
  },
  sectionSubtitle: {
    fontSize: 14,
    color: Colors.textSecondary,
    textAlign: 'center',
    marginBottom: 24,
  },
  featuresGrid: { gap: 16 },
  featureCard: {
    backgroundColor: Colors.bgCard,
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  featureIcon: {
    width: 52,
    height: 52,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  featureTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: Colors.text,
    marginBottom: 6,
  },
  featureDesc: {
    fontSize: 14,
    color: Colors.textSecondary,
    lineHeight: 20,
  },

  levelsSection: { padding: 24, paddingTop: 0 },
  levelCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.bgCard,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  levelIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  levelText: { flex: 1 },
  levelTitle: { fontSize: 16, fontWeight: '600', color: Colors.text },
  levelSub: { fontSize: 12, color: Colors.textSecondary, marginTop: 2 },

  bottomCta: {
    padding: 32,
    alignItems: 'center',
  },
  bottomCtaTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: Colors.text,
    textAlign: 'center',
    marginBottom: 8,
  },
  bottomCtaSub: {
    fontSize: 14,
    color: Colors.textSecondary,
    marginBottom: 24,
    textAlign: 'center',
  },
  bottomCtaBtn: {
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 14,
  },
});
